spring:
  application:
    name: ms-finances-transactions

  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@finances.ol6kb.mongodb.net/?retryWrites=true&w=majority&appName=finances
      database: financesdb

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true